name: github pages

on:
  push:
    branches:
      - master # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: build gh page
        run: yarn run build

      - name: deploy gh page
        uses: Cecilapp/GitHub-Pages-deploy@v2
        env:
          EMAIL: 545360100@qq.com # must be a verified email
          GH_TOKEN: ${{ secrets.GH_PAGE_TOKEN }} # https://github.com/settings/tokens
          BUILD_DIR: ./dist # "_site/" by default